#!/bin/bash
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 0 --data_name Omniglot --model_name cvae --control_name None
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 0 --data_name Omniglot --model_name mcvae --control_name 0.5
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 1 --data_name Omniglot --model_name cvae --control_name None
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 1 --data_name Omniglot --model_name mcvae --control_name 0.5
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 2 --data_name Omniglot --model_name cvae --control_name None
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 2 --data_name Omniglot --model_name mcvae --control_name 0.5
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 3 --data_name Omniglot --model_name cvae --control_name None
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 3 --data_name Omniglot --model_name mcvae --control_name 0.5
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 4 --data_name Omniglot --model_name cvae --control_name None
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 4 --data_name Omniglot --model_name mcvae --control_name 0.5
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 5 --data_name Omniglot --model_name cvae --control_name None
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 5 --data_name Omniglot --model_name mcvae --control_name 0.5
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 6 --data_name Omniglot --model_name cvae --control_name None
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 6 --data_name Omniglot --model_name mcvae --control_name 0.5
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 7 --data_name Omniglot --model_name cvae --control_name None
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 7 --data_name Omniglot --model_name mcvae --control_name 0.5
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 8 --data_name Omniglot --model_name cvae --control_name None
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 8 --data_name Omniglot --model_name mcvae --control_name 0.5
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 9 --data_name Omniglot --model_name cvae --control_name None
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 9 --data_name Omniglot --model_name mcvae --control_name 0.5
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 10 --data_name Omniglot --model_name cvae --control_name None
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 10 --data_name Omniglot --model_name mcvae --control_name 0.5
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 11 --data_name Omniglot --model_name cvae --control_name None
CUDA_VISIBLE_DEVICES="0" python test_generated.py --init_seed 11 --data_name Omniglot --model_name mcvae --control_name 0.5
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 0_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 0_CIFAR10_label_mcvae_0.5
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 1_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 1_CIFAR10_label_mcvae_0.5
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 2_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 2_CIFAR10_label_mcvae_0.5
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 3_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 3_CIFAR10_label_mcvae_0.5
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 4_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 4_CIFAR10_label_mcvae_0.5
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 5_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 5_CIFAR10_label_mcvae_0.5
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 6_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 6_CIFAR10_label_mcvae_0.5
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 7_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 7_CIFAR10_label_mcvae_0.5
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 8_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 8_CIFAR10_label_mcvae_0.5
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 9_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 9_CIFAR10_label_mcvae_0.5
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 10_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 10_CIFAR10_label_mcvae_0.5
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 11_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/inception_score_tf.py npy 11_CIFAR10_label_mcvae_0.5
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 0_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 0_CIFAR10_label_mcvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 1_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 1_CIFAR10_label_mcvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 2_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 2_CIFAR10_label_mcvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 3_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 3_CIFAR10_label_mcvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 4_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 4_CIFAR10_label_mcvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 5_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 5_CIFAR10_label_mcvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 6_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 6_CIFAR10_label_mcvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 7_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 7_CIFAR10_label_mcvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 8_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 8_CIFAR10_label_mcvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 9_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 9_CIFAR10_label_mcvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 10_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 10_CIFAR10_label_mcvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 11_CIFAR10_label_cvae
CUDA_VISIBLE_DEVICES="0" python ./metrics_tf/fid_tf.py npy 11_CIFAR10_label_mcvae
